### ISSUE TITLE
Hadoop Docker issue

### ISSUE THREAD

**Issue by anayyar82** [hjben/docker#1]
Getting master: ssh: connect to host master port 22: Connection refused

Can you confirm how to make it work

**Comment by kwojcikowski** [comment]
This can be solved by setting cgroup version to v1. E.g. by doing the following https://askubuntu.com/a/1399742

**Comment by hjben** [comment]
Hello, I resolved this error.

It was caused by the docker-compose version (V1 -> V2), then the way to give privileges of host cgroup to a container was changed. I commited some actions in the repository, and you must use latest version of docker-compose V2 now.

Thanks for reporting.
