### ISSUE TITLE
Hadoop Docker Issue

### ISSUE THREAD

**Issue by dsaad68** [hjben/docker#2]
```root@master:/# start-yarn.sh
Starting resourcemanager
Starting nodemanagers
: Name or service not knownstname worker1
: Name or service not knownstname master
worker2: Warning: Permanently added 'worker2,10.0.2.4' (ECDSA) to the list of known hosts.
```

I get this message when I start-yarn.sh. In the yarn web interface, it shows that I have one worker. Although I have set upped two.

**Comment by hjben** [comment]
Could you give some more details? I need the number of worker containers, full logs, OS environs, or which command you entered into the console.

**Comment by hjben** [comment]
The warning message occurs when each node starts establishing SSH connections.
I composed the hadoop cluster with one slave but couldn't find any errors in them.
